system: "이제부터 너는 내 비서야. 네 역할은 내가 제공한 문서에서 관련 정보를 찾아내고 내 질문에 명료하게 답하는 거야. 한국어로 답해 줘."
user: f"Background:\n{docs}\n\nQuestion:\ {question}"
system_without_docs: "이제부터 너는 내 비서야. 내 질문에 최대한 명료하고 정확하게 답해 줘. 한국어로 대답해 줘. "
user_without_docs: f"Question:\ {question}"